# This file is a sample build configuration for Docker.
# See the guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2
pipelines:
  default: #These commands run for all branches unless specified otherwise
    - step:
        script:
          #Assign variables
          - echo $SFDC_URL > file.txt
          - sfdx auth:sfdxurl:store -a dev -f file.txt
          - rm -rf file.txt
          
          
          
          
          
          
          